In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])

In [3]:
# 上 3 列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文 55 分、
###數學 60 分、國文 65 分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

# 1.請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
# 2.第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？
# 3.用補考後資料找出與國文成績相關係數最高的學科？

In [4]:
def got_ans(a):
    x=np.nanmax(a)
    y=np.nanmin(a)
    z=np.nanstd(a)
    return x,y,z

In [5]:
en=got_ans(english_score)
ma=got_ans(math_score)
ch=got_ans(chinese_score)
print("max","min","std",en,ma,ch)

max min std (89, 48, 13.433995020924426) (85.0, 60.0, 9.707728879609279) (90, 65, 8.825468196582484)


In [6]:
math_score[np.isnan(math_score)]=55
math_score

array([60., 85., 60., 68., 55., 60.])

In [7]:
new_ma=got_ans(math_score)

In [8]:
np.corrcoef(english_score,chinese_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [9]:
np.corrcoef(math_score,chinese_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [10]:
#ans3=english